### ISSUE TITLE
regex-tdfa-1.2.2 Show instance removed?

### ISSUE THREAD

**Issue by juhp** [ChrisKuklewicz/regex-tdfa#2]
There seems to be a regression in regex-tdfa-1.2.2, which causes:
- [x] jaspervdj/hakyll#420 and jaspervdj/hakyll#422
- [x] ddssff/cabal-debian#54
- [x] yi-editor/yi#797

**Comment by neongreen** [comment]
_sigh_

I should've released it as 1.3.0 instead, right.

@juhp: if your code is affected, the solution is to `import Text.Show.Functions`.

**Comment by juhp** [comment]
Not mine - I am just reporting this on behave of Stackage. :)

**Comment by juhp** [comment]
Okay then probably I should have reported this against Stackage since the change is intentional. Thanks

**Comment by neongreen** [comment]
I could release 1.2.2.1 that undoes the change, deprecate 1.2.2, and then release 1.3.0 with the instance removed, but the problem is that most code out there [seems to not have upper bounds](http://packdeps.haskellers.com/reverse/regex-tdfa) on regex-tdfa anyway, so it's unlikely to help anything. I guess I'll just start making pull requests instead :)

**Comment by juhp** [comment]
hakyll and cabal-debian fixed

**Comment by neongreen** [comment]
@juhp: yi has been fixed as well.

**Comment by neongreen** [comment]
@juhp: can the constraint be removed now? Or is there anything else that should be done?

**Comment by juhp** [comment]
Yep done thanks.  Hopefully should get into the next Stackage Nightly snapshot.

cc @DanBurton

**Comment by juhp** [comment]
I missed one more though:
- [ ] wai-predicates test fpco/stackage#1412
